"""WAL-TAT: transactional, causally ranked ternary conversion."""

from .campaign import (
    accepted_weight_counts,
    atomic_write_json,
    coverage_proportional_nll_gate,
    validate_checkpoint_deletion_target,
    worst_ratio,
)
from .controller import (
    AdaptiveTransactionSizer,
    GateDecision,
    RatioGate,
    TransactionController,
    TransactionSizeDecision,
)
from .compensation import (
    linked_down_group_mask,
    linked_gqa_output_group_mask,
    linked_gqa_query_group_mask,
    linked_output_group_mask,
    structured_channel_candidate_mask,
    structured_down_candidate_mask,
)
from .evaluation import LossMetrics, evaluate_causal_lm
from .moments import CausalMomentCollector
from .mixed import (
    FixedMixedQ2Q4Linear,
    MixedArtifactInstallResult,
    install_mixed_q2_q4_artifact,
    valid_group_weight_count,
)
from .packing import (
    PackedQ2Matrix,
    pack_bool_mask,
    pack_partial_matrix,
    pack_ternary_codes,
    read_packed_matrix,
    true_artifact_bpw,
    unpack_bool_mask,
    unpack_partial_matrix,
    unpack_ternary_codes,
    write_packed_matrix,
)
from .quantization import (
    hard_codes_scales,
    hestia_quantize,
    initial_group_scales,
    q4_g128_physical_bpw,
    q8_g128_physical_bpw,
    q2_g128_physical_bpw,
    transaction_schedule,
    weighted_symmetric_odd_level_project,
    weighted_symmetric_nz4_project,
    weighted_symmetric_q4_project,
    weighted_symmetric_q8_project,
)
from .proxy import (
    ProxyTernaryLinear,
    ProxyTernaryMatrix,
    soft_ternary_proxy,
    soft_ternary_proxy_derivative,
)
from .orchestration import (
    active_campaign_workers,
    common_campaign_frontier,
    load_campaign_state,
    sha256_file,
    synchronize_campaign_frontiers,
)
from .scoring import (
    activation_fisher_group_damage,
    diagonal_ternary_search,
    group_weight_mse,
    select_group_mask,
    sensitivity_decile_mask,
)
from .transaction import (
    AtomicTernaryTransaction,
    TransactionalTernaryLinear,
    TransactionalTernaryMatrix,
)
from .transforms import (
    FixedTernaryLinear,
    TransformedProxyTernaryLinear,
    blockwise_randomized_hadamard,
    inverse_blockwise_randomized_hadamard,
    normalized_hadamard,
    rademacher_signs,
)
from .uncertainty import paired_block_bootstrap_nll
from .wal import HashChainWAL, WALIntegrityError, WALRecord

__all__ = [
    "FixedTernaryLinear",
    "TransformedProxyTernaryLinear",
    "blockwise_randomized_hadamard",
    "inverse_blockwise_randomized_hadamard",
    "normalized_hadamard",
    "rademacher_signs",
    "CausalMomentCollector",
    "FixedMixedQ2Q4Linear",
    "MixedArtifactInstallResult",
    "AdaptiveTransactionSizer",
    "AtomicTernaryTransaction",
    "GateDecision",
    "HashChainWAL",
    "LossMetrics",
    "PackedQ2Matrix",
    "RatioGate",
    "TransactionController",
    "TransactionSizeDecision",
    "TransactionalTernaryLinear",
    "TransactionalTernaryMatrix",
    "WALIntegrityError",
    "WALRecord",
    "activation_fisher_group_damage",
    "accepted_weight_counts",
    "atomic_write_json",
    "coverage_proportional_nll_gate",
    "diagonal_ternary_search",
    "evaluate_causal_lm",
    "group_weight_mse",
    "hard_codes_scales",
    "hestia_quantize",
    "initial_group_scales",
    "install_mixed_q2_q4_artifact",
    "linked_down_group_mask",
    "linked_gqa_output_group_mask",
    "linked_gqa_query_group_mask",
    "linked_output_group_mask",
    "q2_g128_physical_bpw",
    "q4_g128_physical_bpw",
    "q8_g128_physical_bpw",
    "weighted_symmetric_odd_level_project",
    "weighted_symmetric_nz4_project",
    "weighted_symmetric_q4_project",
    "weighted_symmetric_q8_project",
    "paired_block_bootstrap_nll",
    "pack_bool_mask",
    "pack_partial_matrix",
    "pack_ternary_codes",
    "ProxyTernaryLinear",
    "ProxyTernaryMatrix",
    "soft_ternary_proxy",
    "soft_ternary_proxy_derivative",
    "active_campaign_workers",
    "common_campaign_frontier",
    "load_campaign_state",
    "sha256_file",
    "synchronize_campaign_frontiers",
    "select_group_mask",
    "sensitivity_decile_mask",
    "structured_channel_candidate_mask",
    "structured_down_candidate_mask",
    "transaction_schedule",
    "true_artifact_bpw",
    "read_packed_matrix",
    "unpack_bool_mask",
    "unpack_partial_matrix",
    "unpack_ternary_codes",
    "validate_checkpoint_deletion_target",
    "valid_group_weight_count",
    "write_packed_matrix",
    "worst_ratio",
]
